---
linters:
  enable-all: true
  disable:
    - exhaustruct
    - exhaustivestruct
    - godox

linters-settings:
  gofumpt:
    extra-rules: true
  gomnd:
    ignored-numbers: [1,2,3]

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck
        - gochecknoglobals
        - unused
