---
project_name: dodo-stage

before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  - id: plugin
    main: ./cmd/dodo-stage
    env: ["CGO_ENABLED=0"]
    goos: [linux, darwin]

  - id: stagehand
    main: ./cmd/stagehand
    binary: stagehand
    env: ["CGO_ENABLED=0"]
    goos: [linux]

archives:
  - id: plugin
    builds: [plugin]
    format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"

  - id: stagehand
    builds: [stagehand]
    format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
