// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: api/v1alpha1/stage.proto

package v1alpha1

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type      string     `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Box       *Box       `protobuf:"bytes,3,opt,name=box,proto3" json:"box,omitempty"`
	Resources *Resources `protobuf:"bytes,4,opt,name=resources,proto3" json:"resources,omitempty"`
}

func (x *Stage) Reset() {
	*x = Stage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_stage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage) ProtoMessage() {}

func (x *Stage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_stage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage.ProtoReflect.Descriptor instead.
func (*Stage) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_stage_proto_rawDescGZIP(), []int{0}
}

func (x *Stage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Stage) GetBox() *Box {
	if x != nil {
		return x.Box
	}
	return nil
}

func (x *Stage) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

type Box struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User        string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version     string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	AccessToken string `protobuf:"bytes,4,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
}

func (x *Box) Reset() {
	*x = Box{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_stage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Box) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Box) ProtoMessage() {}

func (x *Box) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_stage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Box.ProtoReflect.Descriptor instead.
func (*Box) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_stage_proto_rawDescGZIP(), []int{1}
}

func (x *Box) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Box) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Box) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Box) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type Resources struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpu        int64               `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory     int64               `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Volumes    []*PersistentVolume `protobuf:"bytes,3,rep,name=volumes,proto3" json:"volumes,omitempty"`
	UsbFilters []*UsbFilter        `protobuf:"bytes,4,rep,name=usb_filters,json=usbFilters,proto3" json:"usb_filters,omitempty"`
}

func (x *Resources) Reset() {
	*x = Resources{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_stage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_stage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_stage_proto_rawDescGZIP(), []int{2}
}

func (x *Resources) GetCpu() int64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *Resources) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Resources) GetVolumes() []*PersistentVolume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *Resources) GetUsbFilters() []*UsbFilter {
	if x != nil {
		return x.UsbFilters
	}
	return nil
}

type PersistentVolume struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size int64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *PersistentVolume) Reset() {
	*x = PersistentVolume{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_stage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersistentVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistentVolume) ProtoMessage() {}

func (x *PersistentVolume) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_stage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistentVolume.ProtoReflect.Descriptor instead.
func (*PersistentVolume) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_stage_proto_rawDescGZIP(), []int{3}
}

func (x *PersistentVolume) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type UsbFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	VendorId  string `protobuf:"bytes,2,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	ProductId string `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
}

func (x *UsbFilter) Reset() {
	*x = UsbFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_stage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsbFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsbFilter) ProtoMessage() {}

func (x *UsbFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_stage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsbFilter.ProtoReflect.Descriptor instead.
func (*UsbFilter) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_stage_proto_rawDescGZIP(), []int{4}
}

func (x *UsbFilter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UsbFilter) GetVendorId() string {
	if x != nil {
		return x.VendorId
	}
	return ""
}

func (x *UsbFilter) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type SSHOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname       string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port           int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username       string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	PrivateKeyFile string `protobuf:"bytes,4,opt,name=private_key_file,json=privateKeyFile,proto3" json:"private_key_file,omitempty"`
}

func (x *SSHOptions) Reset() {
	*x = SSHOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_stage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSHOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHOptions) ProtoMessage() {}

func (x *SSHOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_stage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHOptions.ProtoReflect.Descriptor instead.
func (*SSHOptions) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_stage_proto_rawDescGZIP(), []int{5}
}

func (x *SSHOptions) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SSHOptions) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SSHOptions) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SSHOptions) GetPrivateKeyFile() string {
	if x != nil {
		return x.PrivateKeyFile
	}
	return ""
}

type ListStagesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stages []*Stage `protobuf:"bytes,1,rep,name=stages,proto3" json:"stages,omitempty"`
}

func (x *ListStagesResponse) Reset() {
	*x = ListStagesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_stage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStagesResponse) ProtoMessage() {}

func (x *ListStagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_stage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStagesResponse.ProtoReflect.Descriptor instead.
func (*ListStagesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_stage_proto_rawDescGZIP(), []int{6}
}

func (x *ListStagesResponse) GetStages() []*Stage {
	if x != nil {
		return x.Stages
	}
	return nil
}

type GetStageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetStageRequest) Reset() {
	*x = GetStageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_stage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStageRequest) ProtoMessage() {}

func (x *GetStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_stage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStageRequest.ProtoReflect.Descriptor instead.
func (*GetStageRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_stage_proto_rawDescGZIP(), []int{7}
}

func (x *GetStageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetStageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Exist      bool        `protobuf:"varint,2,opt,name=exist,proto3" json:"exist,omitempty"`
	Available  bool        `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	SshOptions *SSHOptions `protobuf:"bytes,4,opt,name=ssh_options,json=sshOptions,proto3" json:"ssh_options,omitempty"`
}

func (x *GetStageResponse) Reset() {
	*x = GetStageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_stage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStageResponse) ProtoMessage() {}

func (x *GetStageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_stage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStageResponse.ProtoReflect.Descriptor instead.
func (*GetStageResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_stage_proto_rawDescGZIP(), []int{8}
}

func (x *GetStageResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetStageResponse) GetExist() bool {
	if x != nil {
		return x.Exist
	}
	return false
}

func (x *GetStageResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *GetStageResponse) GetSshOptions() *SSHOptions {
	if x != nil {
		return x.SshOptions
	}
	return nil
}

type CreateStageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *Stage `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *CreateStageRequest) Reset() {
	*x = CreateStageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_stage_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStageRequest) ProtoMessage() {}

func (x *CreateStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_stage_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStageRequest.ProtoReflect.Descriptor instead.
func (*CreateStageRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_stage_proto_rawDescGZIP(), []int{9}
}

func (x *CreateStageRequest) GetConfig() *Stage {
	if x != nil {
		return x.Config
	}
	return nil
}

type DeleteStageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Force   bool   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	Volumes bool   `protobuf:"varint,3,opt,name=volumes,proto3" json:"volumes,omitempty"`
}

func (x *DeleteStageRequest) Reset() {
	*x = DeleteStageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_stage_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStageRequest) ProtoMessage() {}

func (x *DeleteStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_stage_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStageRequest.ProtoReflect.Descriptor instead.
func (*DeleteStageRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_stage_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteStageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteStageRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *DeleteStageRequest) GetVolumes() bool {
	if x != nil {
		return x.Volumes
	}
	return false
}

type StartStageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *StartStageRequest) Reset() {
	*x = StartStageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_stage_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartStageRequest) ProtoMessage() {}

func (x *StartStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_stage_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartStageRequest.ProtoReflect.Descriptor instead.
func (*StartStageRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_stage_proto_rawDescGZIP(), []int{11}
}

func (x *StartStageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StopStageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *StopStageRequest) Reset() {
	*x = StopStageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_stage_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopStageRequest) ProtoMessage() {}

func (x *StopStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_stage_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopStageRequest.ProtoReflect.Descriptor instead.
func (*StopStageRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_stage_proto_rawDescGZIP(), []int{12}
}

func (x *StopStageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_v1alpha1_stage_proto protoreflect.FileDescriptor

var file_api_v1alpha1_stage_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x73,
	0x74, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2b, 0x63, 0x6f, 0x6d, 0x2e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x64, 0x6f, 0x64, 0x6f, 0x5f, 0x63, 0x6c, 0x69, 0x2e,
	0x64, 0x6f, 0x64, 0x6f, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc9, 0x01, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x42, 0x0a, 0x03, 0x62, 0x6f, 0x78, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x64, 0x6f, 0x64, 0x6f, 0x5f, 0x63, 0x6c, 0x69, 0x2e, 0x64, 0x6f, 0x64, 0x6f, 0x5f,
	0x73, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2e, 0x42, 0x6f, 0x78, 0x52, 0x03, 0x62, 0x6f, 0x78, 0x12, 0x54, 0x0a, 0x09, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x64, 0x6f, 0x64, 0x6f,
	0x5f, 0x63, 0x6c, 0x69, 0x2e, 0x64, 0x6f, 0x64, 0x6f, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x22, 0x6a, 0x0a, 0x03, 0x42, 0x6f, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xe7, 0x01,
	0x0a, 0x09, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x63,
	0x70, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x57, 0x0a, 0x07, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3d, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x64, 0x6f, 0x64, 0x6f, 0x5f, 0x63, 0x6c, 0x69, 0x2e, 0x64, 0x6f, 0x64,
	0x6f, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x56,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x07, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x12, 0x57,
	0x0a, 0x0b, 0x75, 0x73, 0x62, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x64, 0x6f, 0x64, 0x6f, 0x5f, 0x63, 0x6c, 0x69, 0x2e, 0x64, 0x6f, 0x64, 0x6f, 0x5f, 0x73,
	0x74, 0x61, 0x67, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x55, 0x73, 0x62, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x0a, 0x75, 0x73, 0x62,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x22, 0x26, 0x0a, 0x10, 0x50, 0x65, 0x72, 0x73, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x74, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22,
	0x5b, 0x0a, 0x09, 0x55, 0x73, 0x62, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x22, 0x82, 0x01, 0x0a,
	0x0a, 0x53, 0x53, 0x48, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x68,
	0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68,
	0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x46, 0x69, 0x6c,
	0x65, 0x22, 0x60, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x64, 0x6f, 0x64, 0x6f, 0x5f, 0x63, 0x6c, 0x69, 0x2e, 0x64, 0x6f,
	0x64, 0x6f, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x67, 0x65, 0x73, 0x22, 0x25, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xb4, 0x01, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x65, 0x78, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x58, 0x0a, 0x0b, 0x73, 0x73, 0x68, 0x5f, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x64, 0x6f, 0x64, 0x6f, 0x5f, 0x63,
	0x6c, 0x69, 0x2e, 0x64, 0x6f, 0x64, 0x6f, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x53, 0x53, 0x48, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0a, 0x73, 0x73, 0x68, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0x60, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4a, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x64, 0x6f, 0x64, 0x6f, 0x5f, 0x63, 0x6c, 0x69, 0x2e, 0x64, 0x6f,
	0x64, 0x6f, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x22, 0x58, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f,
	0x72, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x22, 0x27, 0x0a,
	0x11, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x10, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x74,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xb2,
	0x06, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x67, 0x65, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x36,
	0x0a, 0x04, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x60, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x37, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x64, 0x6f, 0x64,
	0x6f, 0x5f, 0x63, 0x6c, 0x69, 0x2e, 0x64, 0x6f, 0x64, 0x6f, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x50, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x65, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x74, 0x61, 0x67, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x3f,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x64, 0x6f, 0x64, 0x6f,
	0x5f, 0x63, 0x6c, 0x69, 0x2e, 0x64, 0x6f, 0x64, 0x6f, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x87, 0x01, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x3c, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x64, 0x6f, 0x64, 0x6f, 0x5f, 0x63,
	0x6c, 0x69, 0x2e, 0x64, 0x6f, 0x64, 0x6f, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3d, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x64, 0x6f, 0x64, 0x6f, 0x5f, 0x63, 0x6c, 0x69,
	0x2e, 0x64, 0x6f, 0x64, 0x6f, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x66, 0x0a, 0x0b, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x3f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x64, 0x6f, 0x64, 0x6f, 0x5f, 0x63, 0x6c, 0x69, 0x2e, 0x64,
	0x6f, 0x64, 0x6f, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x66, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x12, 0x3f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x64, 0x6f,
	0x64, 0x6f, 0x5f, 0x63, 0x6c, 0x69, 0x2e, 0x64, 0x6f, 0x64, 0x6f, 0x5f, 0x73, 0x74, 0x61, 0x67,
	0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x64, 0x0a, 0x0a, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x3e, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x64, 0x6f, 0x64, 0x6f, 0x5f, 0x63, 0x6c, 0x69, 0x2e, 0x64, 0x6f,
	0x64, 0x6f, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x62, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x64, 0x6f, 0x64, 0x6f, 0x5f, 0x63,
	0x6c, 0x69, 0x2e, 0x64, 0x6f, 0x64, 0x6f, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x53,
	0x74, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x64, 0x6f, 0x64, 0x6f, 0x2d, 0x63, 0x6c, 0x69, 0x2f, 0x64, 0x6f, 0x64, 0x6f, 0x2d,
	0x73, 0x74, 0x61, 0x67, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1alpha1_stage_proto_rawDescOnce sync.Once
	file_api_v1alpha1_stage_proto_rawDescData = file_api_v1alpha1_stage_proto_rawDesc
)

func file_api_v1alpha1_stage_proto_rawDescGZIP() []byte {
	file_api_v1alpha1_stage_proto_rawDescOnce.Do(func() {
		file_api_v1alpha1_stage_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1alpha1_stage_proto_rawDescData)
	})
	return file_api_v1alpha1_stage_proto_rawDescData
}

var file_api_v1alpha1_stage_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_v1alpha1_stage_proto_goTypes = []interface{}{
	(*Stage)(nil),              // 0: com.github.dodo_cli.dodo_stage.api.v1alpha1.Stage
	(*Box)(nil),                // 1: com.github.dodo_cli.dodo_stage.api.v1alpha1.Box
	(*Resources)(nil),          // 2: com.github.dodo_cli.dodo_stage.api.v1alpha1.Resources
	(*PersistentVolume)(nil),   // 3: com.github.dodo_cli.dodo_stage.api.v1alpha1.PersistentVolume
	(*UsbFilter)(nil),          // 4: com.github.dodo_cli.dodo_stage.api.v1alpha1.UsbFilter
	(*SSHOptions)(nil),         // 5: com.github.dodo_cli.dodo_stage.api.v1alpha1.SSHOptions
	(*ListStagesResponse)(nil), // 6: com.github.dodo_cli.dodo_stage.api.v1alpha1.ListStagesResponse
	(*GetStageRequest)(nil),    // 7: com.github.dodo_cli.dodo_stage.api.v1alpha1.GetStageRequest
	(*GetStageResponse)(nil),   // 8: com.github.dodo_cli.dodo_stage.api.v1alpha1.GetStageResponse
	(*CreateStageRequest)(nil), // 9: com.github.dodo_cli.dodo_stage.api.v1alpha1.CreateStageRequest
	(*DeleteStageRequest)(nil), // 10: com.github.dodo_cli.dodo_stage.api.v1alpha1.DeleteStageRequest
	(*StartStageRequest)(nil),  // 11: com.github.dodo_cli.dodo_stage.api.v1alpha1.StartStageRequest
	(*StopStageRequest)(nil),   // 12: com.github.dodo_cli.dodo_stage.api.v1alpha1.StopStageRequest
	(*empty.Empty)(nil),        // 13: google.protobuf.Empty
	(*PluginInfo)(nil),         // 14: com.github.dodo_cli.dodo_stage.api.v1alpha1.PluginInfo
}
var file_api_v1alpha1_stage_proto_depIdxs = []int32{
	1,  // 0: com.github.dodo_cli.dodo_stage.api.v1alpha1.Stage.box:type_name -> com.github.dodo_cli.dodo_stage.api.v1alpha1.Box
	2,  // 1: com.github.dodo_cli.dodo_stage.api.v1alpha1.Stage.resources:type_name -> com.github.dodo_cli.dodo_stage.api.v1alpha1.Resources
	3,  // 2: com.github.dodo_cli.dodo_stage.api.v1alpha1.Resources.volumes:type_name -> com.github.dodo_cli.dodo_stage.api.v1alpha1.PersistentVolume
	4,  // 3: com.github.dodo_cli.dodo_stage.api.v1alpha1.Resources.usb_filters:type_name -> com.github.dodo_cli.dodo_stage.api.v1alpha1.UsbFilter
	0,  // 4: com.github.dodo_cli.dodo_stage.api.v1alpha1.ListStagesResponse.stages:type_name -> com.github.dodo_cli.dodo_stage.api.v1alpha1.Stage
	5,  // 5: com.github.dodo_cli.dodo_stage.api.v1alpha1.GetStageResponse.ssh_options:type_name -> com.github.dodo_cli.dodo_stage.api.v1alpha1.SSHOptions
	0,  // 6: com.github.dodo_cli.dodo_stage.api.v1alpha1.CreateStageRequest.config:type_name -> com.github.dodo_cli.dodo_stage.api.v1alpha1.Stage
	13, // 7: com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin.Init:input_type -> google.protobuf.Empty
	13, // 8: com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin.GetPluginInfo:input_type -> google.protobuf.Empty
	13, // 9: com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin.ListStages:input_type -> google.protobuf.Empty
	7,  // 10: com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin.GetStage:input_type -> com.github.dodo_cli.dodo_stage.api.v1alpha1.GetStageRequest
	9,  // 11: com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin.CreateStage:input_type -> com.github.dodo_cli.dodo_stage.api.v1alpha1.CreateStageRequest
	10, // 12: com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin.DeleteStage:input_type -> com.github.dodo_cli.dodo_stage.api.v1alpha1.DeleteStageRequest
	11, // 13: com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin.StartStage:input_type -> com.github.dodo_cli.dodo_stage.api.v1alpha1.StartStageRequest
	12, // 14: com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin.StopStage:input_type -> com.github.dodo_cli.dodo_stage.api.v1alpha1.StopStageRequest
	13, // 15: com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin.Init:output_type -> google.protobuf.Empty
	14, // 16: com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin.GetPluginInfo:output_type -> com.github.dodo_cli.dodo_stage.api.v1alpha1.PluginInfo
	6,  // 17: com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin.ListStages:output_type -> com.github.dodo_cli.dodo_stage.api.v1alpha1.ListStagesResponse
	8,  // 18: com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin.GetStage:output_type -> com.github.dodo_cli.dodo_stage.api.v1alpha1.GetStageResponse
	13, // 19: com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin.CreateStage:output_type -> google.protobuf.Empty
	13, // 20: com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin.DeleteStage:output_type -> google.protobuf.Empty
	13, // 21: com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin.StartStage:output_type -> google.protobuf.Empty
	13, // 22: com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin.StopStage:output_type -> google.protobuf.Empty
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_v1alpha1_stage_proto_init() }
func file_api_v1alpha1_stage_proto_init() {
	if File_api_v1alpha1_stage_proto != nil {
		return
	}
	file_api_v1alpha1_stage_plugin_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_v1alpha1_stage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_stage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Box); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_stage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resources); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_stage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersistentVolume); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_stage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsbFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_stage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSHOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_stage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStagesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_stage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_stage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_stage_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_stage_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteStageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_stage_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartStageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_stage_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopStageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1alpha1_stage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1alpha1_stage_proto_goTypes,
		DependencyIndexes: file_api_v1alpha1_stage_proto_depIdxs,
		MessageInfos:      file_api_v1alpha1_stage_proto_msgTypes,
	}.Build()
	File_api_v1alpha1_stage_proto = out.File
	file_api_v1alpha1_stage_proto_rawDesc = nil
	file_api_v1alpha1_stage_proto_goTypes = nil
	file_api_v1alpha1_stage_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StagePluginClient is the client API for StagePlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StagePluginClient interface {
	Init(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	GetPluginInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*PluginInfo, error)
	ListStages(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListStagesResponse, error)
	GetStage(ctx context.Context, in *GetStageRequest, opts ...grpc.CallOption) (*GetStageResponse, error)
	CreateStage(ctx context.Context, in *CreateStageRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteStage(ctx context.Context, in *DeleteStageRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	StartStage(ctx context.Context, in *StartStageRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	StopStage(ctx context.Context, in *StopStageRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type stagePluginClient struct {
	cc grpc.ClientConnInterface
}

func NewStagePluginClient(cc grpc.ClientConnInterface) StagePluginClient {
	return &stagePluginClient{cc}
}

func (c *stagePluginClient) Init(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stagePluginClient) GetPluginInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*PluginInfo, error) {
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, "/com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin/GetPluginInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stagePluginClient) ListStages(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListStagesResponse, error) {
	out := new(ListStagesResponse)
	err := c.cc.Invoke(ctx, "/com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin/ListStages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stagePluginClient) GetStage(ctx context.Context, in *GetStageRequest, opts ...grpc.CallOption) (*GetStageResponse, error) {
	out := new(GetStageResponse)
	err := c.cc.Invoke(ctx, "/com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin/GetStage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stagePluginClient) CreateStage(ctx context.Context, in *CreateStageRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin/CreateStage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stagePluginClient) DeleteStage(ctx context.Context, in *DeleteStageRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin/DeleteStage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stagePluginClient) StartStage(ctx context.Context, in *StartStageRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin/StartStage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stagePluginClient) StopStage(ctx context.Context, in *StopStageRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin/StopStage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StagePluginServer is the server API for StagePlugin service.
type StagePluginServer interface {
	Init(context.Context, *empty.Empty) (*empty.Empty, error)
	GetPluginInfo(context.Context, *empty.Empty) (*PluginInfo, error)
	ListStages(context.Context, *empty.Empty) (*ListStagesResponse, error)
	GetStage(context.Context, *GetStageRequest) (*GetStageResponse, error)
	CreateStage(context.Context, *CreateStageRequest) (*empty.Empty, error)
	DeleteStage(context.Context, *DeleteStageRequest) (*empty.Empty, error)
	StartStage(context.Context, *StartStageRequest) (*empty.Empty, error)
	StopStage(context.Context, *StopStageRequest) (*empty.Empty, error)
}

// UnimplementedStagePluginServer can be embedded to have forward compatible implementations.
type UnimplementedStagePluginServer struct {
}

func (*UnimplementedStagePluginServer) Init(context.Context, *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (*UnimplementedStagePluginServer) GetPluginInfo(context.Context, *empty.Empty) (*PluginInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPluginInfo not implemented")
}
func (*UnimplementedStagePluginServer) ListStages(context.Context, *empty.Empty) (*ListStagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStages not implemented")
}
func (*UnimplementedStagePluginServer) GetStage(context.Context, *GetStageRequest) (*GetStageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStage not implemented")
}
func (*UnimplementedStagePluginServer) CreateStage(context.Context, *CreateStageRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStage not implemented")
}
func (*UnimplementedStagePluginServer) DeleteStage(context.Context, *DeleteStageRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStage not implemented")
}
func (*UnimplementedStagePluginServer) StartStage(context.Context, *StartStageRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartStage not implemented")
}
func (*UnimplementedStagePluginServer) StopStage(context.Context, *StopStageRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopStage not implemented")
}

func RegisterStagePluginServer(s *grpc.Server, srv StagePluginServer) {
	s.RegisterService(&_StagePlugin_serviceDesc, srv)
}

func _StagePlugin_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StagePluginServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StagePluginServer).Init(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StagePlugin_GetPluginInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StagePluginServer).GetPluginInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin/GetPluginInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StagePluginServer).GetPluginInfo(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StagePlugin_ListStages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StagePluginServer).ListStages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin/ListStages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StagePluginServer).ListStages(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StagePlugin_GetStage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StagePluginServer).GetStage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin/GetStage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StagePluginServer).GetStage(ctx, req.(*GetStageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StagePlugin_CreateStage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StagePluginServer).CreateStage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin/CreateStage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StagePluginServer).CreateStage(ctx, req.(*CreateStageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StagePlugin_DeleteStage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StagePluginServer).DeleteStage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin/DeleteStage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StagePluginServer).DeleteStage(ctx, req.(*DeleteStageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StagePlugin_StartStage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartStageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StagePluginServer).StartStage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin/StartStage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StagePluginServer).StartStage(ctx, req.(*StartStageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StagePlugin_StopStage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopStageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StagePluginServer).StopStage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin/StopStage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StagePluginServer).StopStage(ctx, req.(*StopStageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StagePlugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.github.dodo_cli.dodo_stage.api.v1alpha1.StagePlugin",
	HandlerType: (*StagePluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _StagePlugin_Init_Handler,
		},
		{
			MethodName: "GetPluginInfo",
			Handler:    _StagePlugin_GetPluginInfo_Handler,
		},
		{
			MethodName: "ListStages",
			Handler:    _StagePlugin_ListStages_Handler,
		},
		{
			MethodName: "GetStage",
			Handler:    _StagePlugin_GetStage_Handler,
		},
		{
			MethodName: "CreateStage",
			Handler:    _StagePlugin_CreateStage_Handler,
		},
		{
			MethodName: "DeleteStage",
			Handler:    _StagePlugin_DeleteStage_Handler,
		},
		{
			MethodName: "StartStage",
			Handler:    _StagePlugin_StartStage_Handler,
		},
		{
			MethodName: "StopStage",
			Handler:    _StagePlugin_StopStage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1alpha1/stage.proto",
}
